language: go

go:
  - "1.12"

# install is needed because it overrides the default behaviour (which doesn't work)
install:
  - unset GOPATH

# build both the current (v3) and previous versions
script:
  - ./v3/build


