#!/bin/bash -e
# The builtin/threadsafe teemplates provide the primary 'source of truth'.
# This script creates the builtin/fast templates automatically.

cd builtin

cat threadsafe/collection.tpl > fast/collection.tpl

for tpl in list.tpl map.tpl set.tpl; do
  echo $tpl
  cat threadsafe/$tpl | \
      fgrep -v '"sync"' | fgrep -v 'sync.RWMutex' | \
      fgrep -v 's.Lock()' | fgrep -v 's.Unlock()' | \
      fgrep -v 's.RLock()' | fgrep -v 's.RUnlock()' > fast/$tpl
done

cd ../builtintest

function update
{
  if [ threadsafe/$2 -nt $1/$2 ]; then
    echo $1/$2
    echo "package $1"  > $1/$2
    tail -n +2 threadsafe/$2 >> $1/$2
  fi
}

for file in ximap_test.go xiset_test.go; do
  update immutable $file
  update fast      $file
done

for file in xmmap_test.go xmset_test.go; do
  update fast $file
done

update simple xmmap_test.go
