#!/bin/bash -e
# The builtin/threadsafe teemplates provide the primary 'source of truth'.
# This script creates the builtin/fast templates automatically.

cd builtin

cat threadsafe/collection.tpl > fast/collection.tpl

for tpl in list.tpl map.tpl set.tpl; do
  echo $tpl
  cat threadsafe/$tpl | fgrep -v '"sync"' | \
      fgrep -v 'sync.RWMutex' | \
      fgrep -v 's.Lock()' | fgrep -v 's.Unlock()' | \
      fgrep -v 's.RLock()' | fgrep -v 's.RUnlock()' > fast/$tpl
done

cd ../builtintest/threadsafe

for tst in *_test.go; do
  echo $tst
  cat $tst | sed 's#package threadsafe#package fast#' > ../fast/$tst
done
